name: Cucumber Projects Permissions
description: A recipe to project permissions for activated user roles. 
type: Testing
config:
  actions:
    user.role.tester:
      grantPermissions:
        - 'access projects page'
    user.role.developer:
      grantPermissions:
        - 'access projects page'
    user.role.analyst:
      grantPermissions:
        - 'access projects page'
    user.role.designer:
      grantPermissions:
        - 'access projects page'
    user.role.coordinator:
      grantPermissions:
        - 'access projects page'
    user.role.product_owner:
      grantPermissions:
        - 'access projects page'
    user.role.admin:
      grantPermissions:
        - 'access projects page'
