name: Cucumber Components Permissions
description: A recipe to components permissions for activated user roles. 
type: Testing
config:
  actions:
    user.role.tester:
      grantPermissions:
        - 'access components page'
    user.role.developer:
      grantPermissions:
        - 'access components page'
    user.role.analyst:
      grantPermissions:
        - 'access components page'
    user.role.designer:
      grantPermissions:
        - 'access components page'
    user.role.coordinator:
      grantPermissions:
        - 'access components page'
    user.role.product_owner:
      grantPermissions:
        - 'access components page'
    user.role.admin:
      grantPermissions:
        - 'access components page'
    user.role.super_admin:
      grantPermissions:
        - 'access components page'
