name: Cucumber Products Permissions
description: A recipe to product permissions for activated user roles. 
type: Testing
config:
  actions:
    user.role.tester:
      grantPermissions:
        - 'access products page'
    user.role.developer:
      grantPermissions:
        - 'access products page'
    user.role.analyst:
      grantPermissions:
        - 'access products page'
    user.role.designer:
      grantPermissions:
        - 'access products page'
    user.role.coordinator:
      grantPermissions:
        - 'access products page'
    user.role.product_owner:
      grantPermissions:
        - 'access products page'
    user.role.admin:
      grantPermissions:
        - 'access products page'
    user.role.super_admin:
      grantPermissions:
        - 'access products page'
