name: Cucumber products - developer 
description: A recipe to manage needed change of configs for the developer user role.
type: Testing
config:
  actions:
    user.role.developer:
      grantPermissions:
        - 'access products page'
