name: Cucumber projects - designer 
description: A recipe to manage needed change of configs for the designer user role.
type: Testing
config:
  actions:
    user.role.designer:
      grantPermissions:
        - 'access projects page'
