name: Cucumber products - admin 
description: A recipe to manage needed change of configs for the admin user role.
type: Testing
config:
  actions:
    user.role.admin:
      grantPermissions:
        - 'access products page'
